// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DissociateOrphanFav(arg1) {
  return window['go']['main']['App']['DissociateOrphanFav'](arg1);
}
